Feature/polygon boost
bitcoin-verse/verse-clicker pull request #157
Opened 2023-11-28 07:06 UTC by micahpatng

2023-11-28 07:25 UTC, PorlyBe commented on src/components/Boosts/Boosts.tsx
> +          {boostList(player, isPolygon).map(
consider how we'd handle adding other chains in the future... maybe worth doing `boostList(player, chainId)` and having that return only the bonuses available by a specific chain... can test with different bonuses for 1, 5 and 137

2023-11-29 01:43 UTC, micahpatng commented on src/components/Boosts/Boosts.tsx
> +          {boostList(player, isPolygon).map(
that makes sense, fixed!

2023-11-29 01:58 UTC, PorlyBe requested changes

2023-11-29 01:58 UTC, PorlyBe commented on src/components/Boosts/Boosts.tsx
> +      show: isPolygon,
maybe just return different arrays depending on chainid... doing this way would get complicated if different chains end up having different copy or bonus values

2023-11-29 01:58 UTC, PorlyBe commented on src/components/Boosts/Modals/Scratcher.tsx
> +      <LinkButton href="https://scratcher.verse.bitcoin.com/" target="_blank">
will need the isWallet check in here to navigate directly

2023-11-29 01:58 UTC, PorlyBe commented on src/context/reducers/player.ts
> +  bonus: number;
player object with bonuses is little different to this... please remove for now, i updated types in my burn branch

2023-11-29 02:35 UTC, PorlyBe approved these changes

2023-11-29 02:36 UTC, merged