Chore/url generation
bitcoin-verse/verse-clicker pull request #236
Opened 2024-01-16 07:50 UTC by PorlyBe

**Short Description:**

generate dev/prod urls

**Figma Link (optional):**
N/A

**Screenshots (optional):**
N/A

**This PR is blocked by or a continuation of:**
PR#

2024-01-16 09:00 UTC, micahpatng commented on src/components/Boosts/Modals/Farm.tsx
> -        {...(isWallet
based on this code it should only open to new tab when `!isWallet`... right?

2024-01-16 09:05 UTC, micahpatng commented on src/helpers/links.ts
> +    const URL_DEEPLINK = `bitcoincom://buy/`;
is there a reason why you're using back tick instead of `"`

2024-01-16 09:11 UTC, micahpatng requested changes
links are not working too...

2024-01-17 00:42 UTC, PorlyBe commented on src/components/Boosts/Modals/Farm.tsx
> -        {...(isWallet
ah you're right... fixed

2024-01-17 00:42 UTC, PorlyBe commented on src/helpers/links.ts
> +    const URL_DEEPLINK = `bitcoincom://buy/`;
consistency, lol

2024-01-17 01:30 UTC, micahpatng approved these changes
looks gooood!

2024-01-17 01:36 UTC, merged