feat(leaderboard): :sparkles: Adds Leaderboard view, removes Leaderboard from sidebar folder
bitcoin-verse/verse-clicker pull request #275
Opened 2024-02-02 05:13 UTC by ssotomayor

- Leaderboard view :sparkles:
- Adds react-router :sparkles:

2024-02-19 01:17 UTC, PorlyBe requested changes
Finally got around to reviewing this... left some comments, also some more in here

- please rebase onto master
- particles are visible in front of leaderboard
- i think we should separate the components from current (modal) leaderbaord and this page, since they'll have different designs (once we get designers to whip something up)

2024-02-19 01:17 UTC, PorlyBe commented on src/App.tsx
>          <NotConnected />
lets move this and the logic into Main so users can view leaderboard without being connected

2024-02-19 01:17 UTC, PorlyBe commented on src/components/Header/styled.ts
> +  @media (min-width: 0px) {
you shouldn't need this media query.. also `vw` for fontsizes. yikes, lol

2024-02-19 01:17 UTC, PorlyBe commented on src/components/Sidebar/Sidebar.tsx
> +            navigate("/leaderboard");
🤔 thinking lets keep the modal for ingame quick view... navigating back can be a litlte janky when viewed inside verse explorer

2024-02-19 03:33 UTC, ssotomayor commented on src/components/Header/styled.ts
> +  @media (min-width: 0px) {
Oh i needed it because i added 
``` 
<Title>
        Verse {gameMode === "Christmas" ? "Clickmas" : "Clicker"}{" "}
        {pageTitle ? `| ${pageTitle}` : ""}
</Title>
```

And then was passing:
```
<Header pageTitle="Leaderboard" />
```

Specifically for this component, this made the title "Verse Clicker | Leaderboard" which was longer and breaking a bit in phones, i've removed the title now, but i thought it was a nice touch :D

2024-02-19 05:07 UTC, ssotomayor commented
@PorlyBe changes are done, regarding this:
> i think we should separate the components from current (modal) leaderbaord and this page, since they'll have different designs (once we get designers to whip something up)

Components from the specific view are in _src/components/Leaderboard_ and for the Sidebar are within _src/components/Sidebar/Leaderboard_

I understand this can be confusing, but it felt weird to call the folder "LeaderboardView" within "components" open to suggestions tho. 🤔

2024-02-20 07:00 UTC, PorlyBe approved these changes
one small comment but looks good

2024-02-20 07:00 UTC, PorlyBe commented on src/views/Leaderboard.tsx
> +    { label: "Goerli", value: "Goerli" },
can we remove testnets from this if REACT_APP_DEV_ENV=development ??

2024-02-20 16:42 UTC, micahpatng reviewed
I have a few points that I wanna discuss:
- the particles are seen behind the campaign tabs
- maybe we should have a view of the leaderboard when there are no values at all in the campaign? 
- would be nice to have a padding for the leaderboard for mobile
![File (2)](https://github.com/bitcoin-verse/verse-clicker/assets/94164690/f6215c29-e698-4933-9008-aede3d4f3558)

2024-02-21 04:11 UTC, ssotomayor commented on src/views/Leaderboard.tsx
> +    { label: "Goerli", value: "Goerli" },
Done.

2024-02-21 04:12 UTC, ssotomayor commented
@micahpatng what you think? I fixed the particles going through the campaign, made the leaderboard slightly smaller to add gutter on mobile, and changed it to be like this when empty

<img width="364" alt="Screenshot 2024-02-21 at 01 12 47" src="https://github.com/bitcoin-verse/verse-clicker/assets/1304919/f2c6f38b-8e40-4447-9160-0544dfea53a3">

2024-02-21 13:45 UTC, micahpatng commented on src/components/Leaderboard/LeaderboardViewer.tsx
> +            if (index >= 25) {
`if (index >= 25 && addr === address)` maybe?

2024-02-21 13:50 UTC, micahpatng commented on src/components/Leaderboard/LeaderboardViewer.tsx
> +        ) : (
also would be better to have this into separate components so it's more readable? like `{leaderboardItems.length ? </LeaderboardConent> :</EmptyLeaderboard>}`

2024-02-22 00:00 UTC, ssotomayor commented on src/components/Leaderboard/LeaderboardViewer.tsx
> +        ) : (
Done.

2024-02-22 00:02 UTC, ssotomayor commented on src/components/Leaderboard/LeaderboardViewer.tsx
> +            if (index >= 25) {
This logic was copied from:
https://github.com/bitcoin-verse/verse-clicker/blob/1b274e1071bad62137f05bcc1501e0dbbbf2c333/src/components/Sidebar/Leaderboard/Leaderboard.tsx#L54-L68

Which seems like only if the user wallet is above the 25th rank it should be shown, if not it doesn't show the row at all.

I've refactored it now in both components. I wouldn't change much of it atm since it will most likely be changed when the designers spin up something.

2024-02-22 08:26 UTC, micahpatng approved these changes
lgtm, merge it in!

2024-02-22 15:26 UTC, merged